#include "hal_data.h"
#include "stdio.h"
#include "string.h"

#include "./UART_Debug/uart_debug.h"
#include "./Screen/screen.h"
#include "./Screen/screen_ui.h"
#include "./Screen/user_screen.h"
#include "./TIM_Clock/tim_clock.h"
#include "./KEY/key.h"

//extern struINPUT_t struINPUT;

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    R_IOPORT_Open(&g_ioport_ctrl, g_ioport.p_cfg);

    TIM_Clock_Init();
    UART_Debug_Init();
    SCREEN_Init();
    Page_Init();  // 初始化页面系统，显示欢迎页

    Key_Init(); 

    while(1){
        // 在主循环中检测按键事件
//        Key_Event_t event = Key_GetEvent(KEY_1);
//        if (event == KEY_Event_ShortPress)
//        {
//            // 短按处理
//            printf("Key 1 Short Press Detected!\n");
//            Key_ClearEvent(KEY_1);
//        }
//        else if (event == KEY_Event_LongPress)
//        {
//            // 长按处理
//            printf("Key 1 Long Press Detected!\n");
//            Key_ClearEvent(KEY_1);
//        }

        Page_Switch();
        // LCD_Test();
        R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
