#include "hal_data.h"
#include <stdio.h>

#include <FatFs/ff.h>
#include <I2S/i2s.h>
#include <KEY/key.h>
#include <Screen/user_screen.h>
#include <SDHI_SDcard/sdhi_sdcard.h>
#include <TIM_Clock/tim_clock.h>
#include <UART_Debug/uart_debug.h>
#include "sys_info.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

FIL file;       // 文件对象

sys_info g_sys_info = {
    .selected_audio = NULL,
    .page_id = 0,
    .songs_per_page = 4,
    .state = 0
};

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    FATFS fs_handle BSP_ALIGN_VARIABLE(32);       // FATFS文件系统对象（静态变量，保持挂载状态）
    FRESULT fresult;
    FIL file;       // 文件对象

    UART_Debug_Init();
    SCREEN_Init();
    I2S_Init();
    TIM_Clock_Init();

    Page0_Welcome();

    printf("[Main] 准备挂载 SD 卡...\r\n");
    // Mount SD card
    fresult = f_mount(&fs_handle, "1:", 1);  // Use "1:" for SD card
    printf("[Main] f_mount 返回: %d\r\n", fresult);
    if (fresult != FR_OK) {
        printf("[Main] SD卡挂载失败 (代码: %d)\r\n", fresult);
    } else {
        printf("[Main] SD卡挂载成功\r\n");
    }

    printf("[Main] Init OK!\r\n");

    // 扫描 SD 卡根目录下的所有 WAV 文件
    I2S_WavReadAll("1:");

    // 打印所有的歌曲信息
    printf("\r\n===== 播放列表 =====\r\n");
    struAudio_t *audio = I2S_GetPlaylistHead();
    uint16_t index = 0;

    if (audio == NULL)
    {
        printf("[Main] 播放列表为空\r\n");
    }
    else
    {
        while (audio != NULL)
        {
            printf("[%02u] %s\r\n", index + 1, audio->name);
            printf("     文件: %s\r\n", audio->filename);
            printf("     格式: %s, 声道: %u, 采样率: %lu Hz, 位深: %u bit\r\n",
                    (audio->fmt.formatTag == 1) ? "PCM" : "Unknown",
                    audio->fmt.channels,
                    audio->fmt.samplesPerSec,
                    audio->fmt.bits_per_sample);
            uint32_t total_seconds = audio->total_samples / audio->fmt.samplesPerSec;
            uint32_t minutes = total_seconds / 60;
            uint32_t seconds = total_seconds % 60;
            printf("     时长: %lu分%lu秒\r\n", minutes, seconds);
            printf("\r\n");
            audio = audio->next;
            index++;
        }
        printf("===== 共 %u 首歌曲 =====\r\n\r\n", I2S_GetPlaylistCount());
    }

    printf("SDcard Read Speed : %d\r\n",SDCard_MeasureReadSpeed());

    g_sys_info.page_id = 0;
    g_sys_info.selected_audio = I2S_GetAudioById(g_sys_info.page_id);
    if (g_sys_info.selected_audio != NULL)
    {
        g_sys_info.selected_audio->play_status = 3;
        g_sys_info.selected_audio->current_sample = 0;
        g_sys_info.selected_audio->buffer_index = 0;
        g_sys_info.selected_audio->file_opened = 0;
        I2S_OpenWavFile(&file, g_sys_info.selected_audio);
    }

    printf("[Main] Entering main loop...\r\n");

    Input_Event_t input = {0};

    while(1){
        Key_GetInput(&input);
        if(input.event != KEY_Event_NULL){
            printf("[Main] Detected Key Event - ID: %u, Event: %u\r\n", input.id, input.event);
            Key_ClearInput();
            break;  // 退出循环，进入主界面
        }
        R_BSP_SoftwareDelay(1U, BSP_DELAY_UNITS_MICROSECONDS);
    }

    Page1_Main();
    g_sys_info.state = 1;  // 切换到主界面状态

    while(1){
        Page2_SongInfo();
    }

    while(1){
        Key_GetInput(&input);
        if(input.event != KEY_Event_NULL){
            printf("[Main] Key: ID=%u, Event=%u\r\n", input.id, input.event);

            // ========== 按键1：下一首 / 快进 ==========
            if(input.id == 0){
                if(g_sys_info.state == 3){
                    // 详情页：快进 5 秒
                    if(input.event == KEY_Event_ShortPress){
                        uint32_t seek_samples = g_sys_info.selected_audio->fmt.samplesPerSec * 5;
                        uint32_t new_sample = g_sys_info.selected_audio->current_sample + seek_samples;
                        if(new_sample > g_sys_info.selected_audio->total_samples){
                            new_sample = g_sys_info.selected_audio->total_samples;
                        }
                        g_sys_info.selected_audio->current_sample = new_sample;
                        uint32_t seek_offset = g_sys_info.selected_audio->data_offset + (new_sample * g_sys_info.selected_audio->bytes_per_sample);
                        f_lseek(&file, seek_offset);
                        printf("[Main] 快进5秒: %lu -> %lu samples\r\n", g_sys_info.selected_audio->current_sample - seek_samples, new_sample);
                    }
                }
                else {
                    // 其他页面：下一首 / 快进
                    if(input.event == KEY_Event_LongPress){
                        // 长按：下一首
                        if(g_sys_info.state == 2){
                            printf("[Main] 请先暂停播放，再切换歌曲\r\n");
                        }
                        else if(g_sys_info.selected_audio->next != NULL){
                            g_sys_info.selected_audio = g_sys_info.selected_audio->next;
                            g_sys_info.selected_audio->play_status = 3;
                            g_sys_info.selected_audio->current_sample = 0;
                            g_sys_info.selected_audio->buffer_index = 0;
                            g_sys_info.selected_audio->file_opened = 0;
                            I2S_OpenWavFile(&file, g_sys_info.selected_audio);
                        }
                    }
                    else if(input.event == KEY_Event_ShortPress){
                        // 短按：快进 5 秒
                        uint32_t seek_samples = g_sys_info.selected_audio->fmt.samplesPerSec * 5;
                        uint32_t new_sample = g_sys_info.selected_audio->current_sample + seek_samples;
                        if(new_sample > g_sys_info.selected_audio->total_samples){
                            new_sample = g_sys_info.selected_audio->total_samples;
                        }
                        g_sys_info.selected_audio->current_sample = new_sample;
                        uint32_t seek_offset = g_sys_info.selected_audio->data_offset + (new_sample * g_sys_info.selected_audio->bytes_per_sample);
                        f_lseek(&file, seek_offset);
                        printf("[Main] 快进5秒: %lu -> %lu samples\r\n", g_sys_info.selected_audio->current_sample - seek_samples, new_sample);
                    }
                }
            }
            // ========== 按键2：上一首 / 倒退 ==========
            else if(input.id == 1){
                if(g_sys_info.state == 3){
                    // 详情页：倒退 5 秒
                    if(input.event == KEY_Event_ShortPress){
                        uint32_t seek_samples = g_sys_info.selected_audio->fmt.samplesPerSec * 5;
                        uint32_t new_sample = 0;
                        if(g_sys_info.selected_audio->current_sample > seek_samples){
                            new_sample = g_sys_info.selected_audio->current_sample - seek_samples;
                        }
                        g_sys_info.selected_audio->current_sample = new_sample;
                        uint32_t seek_offset = g_sys_info.selected_audio->data_offset + (new_sample * g_sys_info.selected_audio->bytes_per_sample);
                        f_lseek(&file, seek_offset);
                        printf("[Main] 倒退5秒: %lu -> %lu samples\r\n", g_sys_info.selected_audio->current_sample + seek_samples, new_sample);
                    }
                }
                else {
                    // 其他页面：上一首 / 倒退
                    if(input.event == KEY_Event_LongPress){
                        // 长按：上一首
                        if(g_sys_info.state == 2){
                            printf("[Main] 请先暂停播放，再切换歌曲\r\n");
                        }
                        else if(g_sys_info.selected_audio->prev != NULL){
                            g_sys_info.selected_audio = g_sys_info.selected_audio->prev;
                            g_sys_info.selected_audio->play_status = 3;
                            g_sys_info.selected_audio->current_sample = 0;
                            g_sys_info.selected_audio->buffer_index = 0;
                            g_sys_info.selected_audio->file_opened = 0;
                            I2S_OpenWavFile(&file, g_sys_info.selected_audio);
                        }
                    }
                    else if(input.event == KEY_Event_ShortPress){
                        // 短按：倒退 5 秒
                        uint32_t seek_samples = g_sys_info.selected_audio->fmt.samplesPerSec * 5;
                        uint32_t new_sample = 0;
                        if(g_sys_info.selected_audio->current_sample > seek_samples){
                            new_sample = g_sys_info.selected_audio->current_sample - seek_samples;
                        }
                        g_sys_info.selected_audio->current_sample = new_sample;
                        uint32_t seek_offset = g_sys_info.selected_audio->data_offset + (new_sample * g_sys_info.selected_audio->bytes_per_sample);
                        f_lseek(&file, seek_offset);
                        printf("[Main] 倒退5秒: %lu -> %lu samples\r\n", g_sys_info.selected_audio->current_sample + seek_samples, new_sample);
                    }
                }
            }
            // ========== 按键3：播放/暂停 / 详情页返回 ==========
            else if(input.id == 2){
                if(input.event == KEY_Event_ShortPress){
                    // 短按：播放/暂停
                    if(g_sys_info.state == 3){
                        // 详情页：播放/暂停切换（不停止播放）
                        if(g_sys_info.selected_audio->play_status == 3){
                            g_sys_info.selected_audio->play_status = 0;
                            printf("[Main] 继续播放\r\n");
                        }
                        else {
                            g_sys_info.selected_audio->play_status = 3;
                            printf("[Main] 暂停播放\r\n");
                        }
                    }
                    else if(g_sys_info.selected_audio->play_status == 3){
                        // 其他页面：暂停中 -> 开始播放
                        g_sys_info.selected_audio->play_status = 0;
                        printf("[Main] 开始播放\r\n");
                        g_sys_info.state = 2;
                    }
                    else {
                        // 其他页面：播放中 -> 暂停
                        g_sys_info.selected_audio->play_status = 3;
                        printf("[Main] 暂停播放\r\n");
                        g_sys_info.state = 1;
                    }
                }
                else if(input.event == KEY_Event_LongPress){
                    // 长按：详情页返回主界面 / 其他页面进入详情页
                    if(g_sys_info.state == 3){
                        // 详情页：返回歌曲列表
                        g_sys_info.state = 1;
                        printf("[Main] 返回歌曲列表\r\n");
                    }
                    else if(g_sys_info.state == 1 || g_sys_info.state == 2){
                        // 其他页面：进入详情页
                        if(g_sys_info.state == 2){
                            // 播放中，先暂停
                            g_sys_info.selected_audio->play_status = 3;
                        }
                        g_sys_info.state = 3;
                        printf("[Main] 进入详情页\r\n");
                    }
                }
            }
            // ========== 按键4：返回主界面 ==========
            else if(input.id == 3){
                if(input.event == KEY_Event_ShortPress || input.event == KEY_Event_LongPress){
                    // 详情页返回主界面
                    if(g_sys_info.state == 3){
                        g_sys_info.state = 1;
                        printf("[Main] 返回主界面\r\n");
                    }
                }
            }

            Key_ClearInput();
        }

        // 根据状态显示不同界面
        if(g_sys_info.state == 1){
            Page1_Main();
        }
        else if(g_sys_info.state == 3){
            Page2_SongInfo();
        }

        // 测量 I2S_PlayWavFile 运行时间
        if(g_sys_info.state == 1 || g_sys_info.state == 2 || g_sys_info.state == 3){
            if(I2S_PlayWavFile(&file, g_sys_info.selected_audio) == WAV_Finish){
                g_sys_info.selected_audio->play_status = 2;
                g_sys_info.state = 1;  // 播放完成返回主界面
                printf("[Main] 播放完成\r\n");
            }
        }
    }



    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
