#include "hal_data.h"
#include <stdio.h>

#include <FatFs/ff.h>
#include <I2S/i2s.h>
#include <KEY/key.h>
#include <Screen/user_screen.h>
#include <SDHI_SDcard/sdhi_sdcard.h>
#include <TIM_Clock/tim_clock.h>
#include <UART_Debug/uart_debug.h>
#include "sys_info.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

sys_info g_sys_info = {
    .selected_audio = NULL,
    .page = 0,
    .is_play = false,
    .input = {0}
};

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    FATFS fs_handle BSP_ALIGN_VARIABLE(32);       // FATFS文件系统对象（静态变量，保持挂载状态）
    FRESULT fresult;
    FIL file;       // 文件对象

    UART_Debug_Init();
    SPI_ST7735_Init();
    SCREEN_Init();
    I2S_Init();
    TIM_Clock_Init();

    Page0_Welcome();

    fresult = f_mount(&fs_handle, "1:", 1);  // Use "1:" for SD card
    if (fresult != FR_OK) {
        printf("[Main] f_mount 返回: %d\r\n", fresult);
        printf("[Main] SD卡挂载失败 (代码: %d)\r\n", fresult);
    } else {
        printf("[Main] SD卡挂载成功\r\n");
    }

    printf("[Main] Init OK!\r\n");

    // 扫描 SD 卡根目录下的所有 WAV 文件
    I2S_WavReadAll("1:");

    // 打印所有的歌曲信息
    printf("\r\n===== 播放列表 =====\r\n");
    struAudio_t *audio = I2S_GetPlaylistHead();
    uint16_t index = 0;

    if (audio == NULL)
    {
        printf("[Main] 播放列表为空\r\n");
    }
    else
    {
        while (audio != NULL)
        {
            printf("[%02u] %s\r\n", index + 1, audio->name);
            printf("     文件: %s\r\n", audio->filename);
            printf("     格式: %s, 声道: %u, 采样率: %lu Hz, 位深: %u bit\r\n",
                    (audio->fmt.formatTag == 1) ? "PCM" : "Unknown",
                    audio->fmt.channels,
                    audio->fmt.samplesPerSec,
                    audio->fmt.bits_per_sample);
            uint32_t total_seconds = audio->total_samples / audio->fmt.samplesPerSec;
            uint32_t minutes = total_seconds / 60;
            uint32_t seconds = total_seconds % 60;
            printf("     时长: %lu分%lu秒\r\n", minutes, seconds);
            printf("\r\n");
            audio = audio->next;
            index++;
        }
        printf("===== 共 %u 首歌曲 =====\r\n\r\n", I2S_GetPlaylistCount());
    }

    printf("SDcard Read Speed : %d\r\n",SDCard_MeasureReadSpeed());

    g_sys_info.selected_audio = I2S_GetPlaylistHead();
    if (g_sys_info.selected_audio != NULL)
    {
        I2S_OpenWavFile(&file, g_sys_info.selected_audio);
    }

    printf("[Main] Entering main loop...\r\n");

    while(1){
        Key_GetInput(&g_sys_info.input);
        if(g_sys_info.input.event != KEY_Event_NULL){
            printf("[Main] Detected Key Event - ID: %u, Event: %u\r\n", g_sys_info.input.id+1, g_sys_info.input.event);
            Key_ClearInput();
            break;  // 退出循环，进入主界面
        }
        R_BSP_SoftwareDelay(1U, BSP_DELAY_UNITS_MICROSECONDS);
    }
    
    g_sys_info.page = 1;  // 切换到主界面状态
    Page1_Main();

    while(1){
        Key_GetInput(&g_sys_info.input);
        if(g_sys_info.input.event != KEY_Event_NULL){
            printf("[Main] Key: ID=%u, Event=%u\r\n", g_sys_info.input.id+1, g_sys_info.input.event);

            //如果在页面一 歌曲选择列表
            if(g_sys_info.page == 1){
                if(g_sys_info.input.id == 0 && g_sys_info.input.event == KEY_Event_ShortPress){
                    if(g_sys_info.selected_audio->next != NULL){
                        I2S_CloseWavFile(&file, g_sys_info.selected_audio);
                        g_sys_info.selected_audio = g_sys_info.selected_audio->next;
                        I2S_OpenWavFile(&file, g_sys_info.selected_audio);

                        // Page1_Main();
                    }
                }
                else if(g_sys_info.input.id == 1 && g_sys_info.input.event == KEY_Event_ShortPress){
                    if(g_sys_info.selected_audio->prev != NULL){
                        I2S_CloseWavFile(&file, g_sys_info.selected_audio);
                        g_sys_info.selected_audio = g_sys_info.selected_audio->prev;
                        I2S_OpenWavFile(&file, g_sys_info.selected_audio);

                        // Page1_Main();
                    }
                }
                else if(g_sys_info.input.id == 2 && g_sys_info.input.event == KEY_Event_ShortPress){
                    if(g_sys_info.is_play == false){
                        g_sys_info.is_play = true;
                    }else{
                        g_sys_info.is_play = false;
                    }
                }
                else if(g_sys_info.input.id == 3 && g_sys_info.input.event == KEY_Event_ShortPress){
                    // 按键3：快进5秒
                    uint32_t skip_samples = g_sys_info.selected_audio->fmt.samplesPerSec * 5;
                    if(g_sys_info.selected_audio->current_sample + skip_samples < g_sys_info.selected_audio->total_samples){
                        g_sys_info.selected_audio->current_sample += skip_samples;
                    }else{
                        g_sys_info.selected_audio->current_sample = g_sys_info.selected_audio->total_samples;
                    }
                    // 更新文件指针位置
                    uint32_t new_offset = g_sys_info.selected_audio->data_offset +
                                       g_sys_info.selected_audio->current_sample * g_sys_info.selected_audio->bytes_per_sample;
                    f_lseek(&file, new_offset);
                    // 重置缓冲区
                    g_sys_info.selected_audio->play_status = 0;
                    g_sys_info.selected_audio->buffer_index = 0;
                }
                else if(g_sys_info.input.id == 4 && g_sys_info.input.event == KEY_Event_ShortPress){
                    // 按键4：回退5秒
                    uint32_t skip_samples = g_sys_info.selected_audio->fmt.samplesPerSec * 5;
                    if(g_sys_info.selected_audio->current_sample > skip_samples){
                        g_sys_info.selected_audio->current_sample -= skip_samples;
                    }else{
                        g_sys_info.selected_audio->current_sample = 0;
                    }
                    // 更新文件指针位置
                    uint32_t new_offset = g_sys_info.selected_audio->data_offset +
                                       g_sys_info.selected_audio->current_sample * g_sys_info.selected_audio->bytes_per_sample;
                    f_lseek(&file, new_offset);
                    // 重置缓冲区
                    g_sys_info.selected_audio->play_status = 0;
                    g_sys_info.selected_audio->buffer_index = 0;
                }
                else if(g_sys_info.input.id == 5 && g_sys_info.input.event == KEY_Event_ShortPress){
                    g_sys_info.page = 2;
                }
            }

            //如果在页面二 
            else if(g_sys_info.page == 2){
                if(g_sys_info.input.id == 5 && g_sys_info.input.event == KEY_Event_ShortPress){
                    g_sys_info.page = 1;
                }
            }

            Key_ClearInput();
        }
        if(g_sys_info.page == 1){
            Page1_Main();
        }
        else if(g_sys_info.page == 2){
            Page2_SongInfo();
        }

        if(g_sys_info.is_play == true){
            if(I2S_PlayWavFile(&file,g_sys_info.selected_audio) == WAV_Finish){
                g_sys_info.selected_audio->play_status = 0;        // 重置为未播放状态
                g_sys_info.selected_audio->current_sample = 0;     // 重置播放位置
                g_sys_info.selected_audio->buffer_index = 0;       // 重置缓冲区索引
                // 文件指针移回数据区开头
                f_lseek(&file, g_sys_info.selected_audio->data_offset);
                g_sys_info.is_play = false;
            }
        }
        
    }



    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
