#include "hal_data.h"
#include ".\UART_debug\uart_debug.h"
#include ".\Screen\screen_ui.h"
#include ".\sys_time\sys_time.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    UART_debug_Init();
    SysTime_Init();      // 初始化系统时间计数器
    SCREEN_Init();

    uint32_t Time = 0x00;
    uint8_t screen_num = 0;  // 界面编号

    while(1){
        if(screen_num == 0) {
            // === 界面1：基础图形 + UI组件测试 ===
            // 1. FillScreen: 黑色背景
            SCREEN_FillScreen(SCREEN_BLACK);

            // 2. DrawString: 标题
            SCREEN_DrawString(30, 2, "Screen 1",
                &Font_8x12_consolas, SCREEN_YELLOW, SCREEN_Nor);

            // 3. DrawLine: 灰色分隔线
            SCREEN_DrawLine(2, 125, 14, 14,
                SCREEN_RED, SCREEN_Nor);

            // 4. DrawPixel: 像素点 (红绿黄)
            SCREEN_DrawPixel(3,  19, SCREEN_RED,   SCREEN_Nor);
            SCREEN_DrawPixel(6,  19, SCREEN_GREEN, SCREEN_Nor);
            SCREEN_DrawPixel(9,  19, SCREEN_YELLOW,  SCREEN_Nor);

            // 5. DrawChar: 单字符
            SCREEN_DrawChar(16, 17, 'A',
                &Font_8x12_consolas, SCREEN_GREEN, SCREEN_Nor);

            // 6. DrawRectSolid: 实心矩形
            SCREEN_DrawRectSolid(30, 60, 18, 38,
                SCREEN_RED, SCREEN_Nor);

            // 7. DrawRectHollow: 空心矩形
            SCREEN_DrawRectHollow(65, 95, 18, 38,
                SCREEN_GREEN, SCREEN_Nor);

            // 8. DrawQuarArc: 四段圆弧组成圆形
            SCREEN_DrawQuarArc(112, 28, 10,
                SCREEN_Quarter1 | SCREEN_Quarter2
                | SCREEN_Quarter3 | SCREEN_Quarter4,
                SCREEN_YELLOW, SCREEN_Nor);

            // 9. DrawHorLine: 水平线
            DrawHorLine(3, 55, 44, SCREEN_RED, SCREEN_Nor);

            // 10. DrawVerLine: 垂直线
            DrawVerLine(60, 44, 68, SCREEN_GREEN, SCREEN_Nor);

            // 11. DrawLine: 对角线 (正常模式)
            SCREEN_DrawLine(66, 100, 48, 68,
                SCREEN_YELLOW, SCREEN_Nor);

            // 12. DrawLine: 对角线 (XOR模式, 与上一条叠加变黑)
            SCREEN_DrawLine(68, 98, 50, 66,
                SCREEN_YELLOW, SCREEN_Xor);

            // 13. DrawButton: 按钮组件
            struUI_Button_t btn = {
                .location = {25, 88},
                .frame = {30, 14, 3},
                .label = "OK",
                .ascii_font = (struFont_t *)&Font_8x12_consolas,
                .hz_font = NULL,
                .color = {SCREEN_GREEN, SCREEN_BLACK, SCREEN_YELLOW},
                .state = 0x00
            };
            SCREEN_DrawButton(&btn);

            // 14. DrawProgressBar: 进度条
            struUI_ProgressBar_t bar = {
                .location = {90, 88},
                .frame = {40, 8},
                .color = {SCREEN_RED, SCREEN_GREEN},
                .progress = 75
            };
            SCREEN_DrawProgressBar(&bar);

            screen_num = 1;
        } else {
            // === 界面2：进阶图形 + UTF + 图片测试 ===
            // printf(">> S2 start\r\n");

            // 1. FillScreen: 深蓝色背景
            SCREEN_FillScreen(SCREEN_COLOR565(10, 10, 40));
            // printf(">> S2-1 FillScreen OK\r\n");

            // 2. DrawString: 标题
            SCREEN_DrawString(30, 2, "Screen 2",
                &Font_8x12_consolas, SCREEN_YELLOW, SCREEN_Nor);
            // printf(">> S2-2 DrawString OK\r\n");

            // 3. DrawLine: 灰色分隔线
            SCREEN_DrawLine(2, 125, 14, 14,
                SCREEN_RED, SCREEN_Nor);
            // printf(">> S2-3 DrawLine OK\r\n");

            // 4. DrawRoundRectSolid: 实心圆角矩形
            SCREEN_DrawRoundRectSolid(3, 55, 18, 42, 6,
                SCREEN_RED, SCREEN_Nor);
            // printf(">> S2-4 RoundRectSolid OK\r\n");

            // 5. DrawRoundRectHollow: 空心圆角矩形
            SCREEN_DrawRoundRectHollow(68, 122, 18, 42, 6,
                SCREEN_GREEN, SCREEN_Nor);
            // printf(">> S2-5 RoundRectHollow OK\r\n");

            // 6. DrawQuarSector: 扇形-右半圆
            SCREEN_DrawQuarSector(30, 59, 14,
                SCREEN_Quarter1 | SCREEN_Quarter4,
                SCREEN_YELLOW, SCREEN_Nor);
            // printf(">> S2-6 Sector1 OK\r\n");

            // 7. DrawQuarSector: 扇形-左半圆
            SCREEN_DrawQuarSector(100, 59, 14,
                SCREEN_Quarter2 | SCREEN_Quarter3,
                SCREEN_GREEN, SCREEN_Nor);
            // printf(">> S2-7 Sector2 OK\r\n");

            // 8. DrawUTFChar: 单个中文字符
            SCREEN_DrawUTFChar(55, 48, "\xe6\xb5\x8b",
                &Font_UTF_16x12_YuMincho, SCREEN_YELLOW, SCREEN_Nor);
            // printf(">> S2-8 UTFChar OK\r\n");

            // 9. DrawImage: 单色图片 (苹果 32x32)
            SCREEN_DrawImage(5, 75, 32, 32,
                gImage_apple, SCREEN_GREEN, SCREEN_Nor);
            // printf(">> S2-9 DrawImage OK\r\n");

            // 10. DrawRGBImage: RGB图片 (32x32)
            SCREEN_DrawRGBImage(42, 75, 32, 32,
                gImage_RGB_163music, SCREEN_Nor);
            // printf(">> S2-10 RGBImage OK\r\n");

            // 11. DrawUTFString: 中文字符串
            SCREEN_DrawUTFString(5, 110, "\xe6\xb5\x8b\xe8\xaf\x95\xe5\xae\x8c\xe6\x88\x90",
                &Font_8x12_consolas, &Font_UTF_16x12_YuMincho,
                SCREEN_YELLOW, SCREEN_Nor);
            // printf(">> S2-11 UTFString OK\r\n");

            // 12. DrawTooltip: 提示框
            struUI_Tooltip_t tip = {
                .location = {95, 118},
                .frame = {48, 12},
                .text = "Pass!",
                .ascii_font = (struFont_t *)&Font_8x12_consolas,
                .hz_font = NULL,
                .color = {SCREEN_RED, SCREEN_YELLOW}
            };
            SCREEN_DrawTooltip(&tip);
            // printf(">> S2-12 Tooltip OK\r\n");

            screen_num = 0;
        }

        Time = SCREEN_RefreshScreen();
        R_BSP_SoftwareDelay(1000U, BSP_DELAY_UNITS_MILLISECONDS);

        printf("[界面%d] Refresh: %ldms\r\n", screen_num == 0 ? 2 : 1, Time);
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
