#include "hal_data.h"
#include "UART_debug/uart_debug.h"
#include "FatFS/ff.h"
#include "sys_time/sys_time.h"

/* SD卡事先格式化为 Fat32 512字节 ，具体配置如有更改请参考ffconf.h文件 ,文件里面部分配置已经做出更改 */
/* FatFS的官方网址是 https://elm-chan.org/fsw/ff/ */
/* 本代码采用的FatFS源码版本是最新(?)的 R0.16 */

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    SysTime_Init();
    UART_debug_Init();

    printf("Hello World!\r\n");

    /* FatFS mount test */
    FATFS FatFS;
    FRESULT result;

    printf("\r\n=== FatFS Mount Test ===\r\n");
    printf("Initializing SD card hardware...\r\n");

    result = f_mount(&FatFS, "1:", 1);
    if (result == FR_OK) {
        printf("[OK] FatFS mount successful!\r\n");
    } else {
        printf("[ERR] FatFS mount failed: %d\r\n", result);
    }

    while(1){

    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
