#include "hal_data.h"
#include <UART_Debug/uart_debug.h>
#include <I2C_MPU6050/mpu6050.h>
#include <I2C_MPU6050/kalman.h>
#include <stdio.h>
#include <math.h>

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    UART_debug_Init();
    printf("MPU6050 Test\r\n");

    if (MPU_Init() == 0)
        printf("MPU6050 Init OK!\r\n");
    else
        printf("MPU6050 Init Failed!\r\n");

    short ax, ay, az;
    short gx, gy, gz;

    kalman_t kf_roll, kf_pitch;
    kalman_init(&kf_roll);
    kalman_init(&kf_pitch);

    const float dt = 0.005f;

    while (1)
    {
        MPU_Get_Accelerometer(&ax, &ay, &az);
        MPU_Get_Gyroscope(&gx, &gy, &gz);

        /* 加速度计计算角度(度) */
        float acc_roll  = atan2f((float)ay, (float)az) * 57.29578f;
        float acc_pitch = atan2f(-(float)ax, (float)sqrtf((float)ay * ay + (float)az * az)) * 57.29578f;

        /* 陀螺仪角速度(度/秒), MPU6050 ±2000dps -> 16.4 LSB/(°/s) */
        float gyro_roll  = (float)gx / 16.4f;
        float gyro_pitch = (float)gy / 16.4f;

        /* 卡尔曼滤波融合 */
        float roll  = kalman_update(&kf_roll,  acc_roll,  gyro_roll,  dt);
        float pitch = kalman_update(&kf_pitch, acc_pitch, gyro_pitch, dt);

        int roll_i  = (int)(roll * 10);
        int pitch_i = (int)(pitch * 10);
        printf("Roll:%d.%d Pitch:%d.%d\r\n", roll_i / 10, abs(roll_i) % 10, pitch_i / 10, abs(pitch_i) % 10);

        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_MILLISECONDS);
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
